export interface FakeUsers {}

[
  {
    name: 'Son Goku',
    lastName: 'Kakarotto',
    email: 'saiyan.spirit@dbzmail.com',
    phoneNumber: '0912345678',
    address: 'Montaña Paoz',
    dni: '1712345678',
    password: 'kamehameha123',
  },
  {
    name: 'Bob',
    lastName: 'Esponja Pantalones Cuadrados',
    email: 'soyready@bikinibottom.com',
    phoneNumber: '0923456789',
    address: 'Calle Concha 124',
    dni: '0923456781',
    password: 'piña_debajo_del_mar',
  },
  {
    name: 'Ben',
    lastName: 'Tennyson',
    email: 'hero.watch10@plumber.net',
    phoneNumber: '0934567890',
    address: 'Bellwood',
    dni: '0104567892',
    password: 'omnitrix2005',
  },
  {
    name: 'Vegeta',
    lastName: 'Príncipe',
    email: 'final.flash@capsulecorp.com',
    phoneNumber: '0945678901',
    address: 'Corporación Cápsula',
    dni: '1105678903',
    password: 'insecto_9000',
  },
  {
    name: 'Patricio',
    lastName: 'Estrella',
    email: 'no_es_la_krusty_krab@underarock.com',
    phoneNumber: '0956789012',
    address: 'Bajo una piedra',
    dni: '0806789014',
    password: 'mayonesa_instrumento',
  },
  {
    name: 'Gwen',
    lastName: 'Tennyson',
    email: 'lucky.girl@magic.com',
    phoneNumber: '0967890123',
    address: 'Bellwood',
    dni: '1707890125',
    password: 'mana_energy10',
  },
  {
    name: 'Calamardo',
    lastName: 'Tentáculos',
    email: 'clarinet.master@art.com',
    phoneNumber: '0978901234',
    address: 'Calle Concha 122',
    dni: '0908901236',
    password: 'odio_a_bob',
  },
  {
    name: 'Piccolo',
    lastName: 'Daimaku',
    email: 'special.beam@namek.com',
    phoneNumber: '0989012345',
    address: 'Desierto',
    dni: '0109012347',
    password: 'meditacion_pura',
  },
  {
    name: 'Kevin',
    lastName: 'Levin',
    email: 'metal.absorb@osmosian.com',
    phoneNumber: '0990123456',
    address: 'Taller Mecánico',
    dni: '1310123458',
    password: 'carro_nuevo11',
  },
  {
    name: 'Eugene',
    lastName: 'Cangrejo',
    email: 'money.lover@krustykrab.com',
    phoneNumber: '0901234567',
    address: 'El Ancla',
    dni: '0711234569',
    password: 'formula_secreta$$',
  },
  {
    name: 'Yugi',
    lastName: 'Muto',
    email: 'king.games@duellinks.com',
    phoneNumber: '0987654321',
    address: 'Tienda de Juegos Kame',
    dni: '0101234567',
    password: 'corazon_de_las_cartas',
  },
  {
    name: 'Finn',
    lastName: 'el Humano',
    email: 'hero.finn@ooo.com',
    phoneNumber: '0981239874',
    address: 'Casa del Árbol',
    dni: '1712344321',
    password: 'matematico123',
  },
  {
    name: 'Seto',
    lastName: 'Kaiba',
    email: 'ceo@kaibacorp.com',
    phoneNumber: '0999999999',
    address: 'Torre Kaiba',
    dni: '0909090909',
    password: 'blue_eyes_white_dragon',
  },
  {
    name: 'Jake',
    lastName: 'el Perro',
    email: 'jake.the.dog@magical.com',
    phoneNumber: '0976543210',
    address: 'Casa del Árbol',
    dni: '0707654321',
    password: 'tocino_frito',
  },
  {
    name: 'Joey',
    lastName: 'Wheeler',
    email: 'brooklyn.rage@duel.net',
    phoneNumber: '0965432109',
    address: 'Ciudad Domino',
    dni: '1301301301',
    password: 'red_eyes_b_dragon',
  },
  {
    name: 'Marceline',
    lastName: 'Abadeer',
    email: 'vampire.queen@nightosphere.com',
    phoneNumber: '0954321098',
    address: 'Cueva de Marceline',
    dni: '1101101102',
    password: 'bajo_de_hacha',
  },
  {
    name: 'Maximillion',
    lastName: 'Pegasus',
    email: 'creator@industrialillusions.com',
    phoneNumber: '0943210987',
    address: 'Reino de los Duelistas',
    dni: '1515151515',
    password: 'eye_of_anubis',
  },
  {
    name: 'Bonnibel',
    lastName: 'Dulce Princesa',
    email: 'science.bubblegum@candykingdom.gov',
    phoneNumber: '0932109876',
    address: 'Castillo de Dulce Reino',
    dni: '1708765432',
    password: 'metodo_cientifico',
  },
  {
    name: 'Mai',
    lastName: 'Valentine',
    email: 'harpie.lady@sky.com',
    phoneNumber: '0921098765',
    address: 'Las Vegas',
    dni: '0808080808',
    password: 'aroma_de_victoria',
  },
  {
    name: 'Simon',
    lastName: 'Petrikov',
    email: 'ice.king@icekingdom.com',
    phoneNumber: '0910987654',
    address: 'Reino Helado',
    dni: '0102030405',
    password: 'gunter_no_toques',
  },
  {
    name: 'Ash',
    lastName: 'Ketchum de Pueblo Paleta',
    email: 'pika_master@kanto.com',
    phoneNumber: '0915151515',
    address: 'Ruta 1, Casa de Delia',
    dni: '0900000151',
    password: 'hazte_con_todos_123',
  },
  {
    name: 'Brock',
    lastName: 'Harrison de Ciudad Plateada',
    email: 'onix_rock@pewtercity.gym',
    phoneNumber: '0987654321',
    address: 'Gimnasio Roca s/n',
    dni: '0900000095',
    password: 'amo_las_enfermeras_joy',
  },
  {
    name: 'Misty',
    lastName: 'Williams de Ciudad Celeste',
    email: 'water_star@ceruleancity.gym',
    phoneNumber: '0998877665',
    address: 'Gimnasio Agua, Calle Cascada',
    dni: '0900000120',
    password: 'odio_los_tipo_bicho',
  },
  {
    name: 'Gary',
    lastName: 'Oak El Campeón',
    email: 'el_mejor_gary@pallet.com',
    phoneNumber: '0900000001',
    address: 'Mansión Oak, Avenida Victoria',
    dni: '0900000150',
    password: 'huelelo_luego_abuelo',
  },
  {
    name: 'James',
    lastName: 'Morgan del Team Rocket',
    email: 'preparense_para_los_problemas@meowth.com',
    phoneNumber: '0966666666',
    address: 'Globo Meowth, El Cielo',
    dni: '0912345678',
    password: 'el_equipo_rocket_vence_otra_vez',
  },
];
